spring:
  thymeleaf:
    mode: LEGACYHTML5
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:mysql://121.42.201.69:3306/yibantest_signname
    username: yiban
    password: yiban
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8082